### PR TITLE
Update ledger_app.toml (add stax)

### PR DESCRIPTION
**Pull request by tdejoigny-ledger**

### CODE REVIEW

**Comment by chris124567** [comment]
The NanoSP icon error I can fix but the other error is because the Stax icon is too large.  That's because we made it 64x64 like the documentation said.  Do you want me to change it back?

**Comment by tdejoigny-ledger** [comment]
@chris124567 we have 2 icons one for the dashboard 32x32 and one inside the app 64x64
please refer to https://developers.ledger.com/docs/device-app/deliver/deliverables/icons#stax-template
and you can also check in our boilerplate app https://github.com/LedgerHQ/app-boilerplate

In addition, you have to update the Stax snapshots to fix the tests (UI has been slightly updated in the last API level)

**Comment by chris124567** [comment]
> @chris124567 we have 2 icons one for the dashboard 32x32 and one inside the app 64x64 please refer to https://developers.ledger.com/docs/device-app/deliver/deliverables/icons#stax-template and you can also check in our boilerplate app https://github.com/LedgerHQ/app-boilerplate
> 
> In addition, you have to update the Stax snapshots to fix the tests (UI has been slightly updated in the last API level)

What do I set `ICON_STAX` in the Makefile to, a 32x32 image or a 64x64 image?  In the Boilerplate app it is a 32x32 image: https://github.com/LedgerHQ/app-boilerplate/blob/master/Makefile#L44.  But the documentation says inside the app should be 64x64.

I also don't understand where I am supposed to set the dashboard icon because I can't find any reference to it in the boilerplate app: https://github.com/search?q=repo%3ALedgerHQ%2Fapp-boilerplate%20dashboard&type=code.

**Comment by tdejoigny-ledger** [comment]
> > @chris124567 we have 2 icons one for the dashboard 32x32 and one inside the app 64x64 please refer to https://developers.ledger.com/docs/device-app/deliver/deliverables/icons#stax-template and you can also check in our boilerplate app https://github.com/LedgerHQ/app-boilerplate
> > In addition, you have to update the Stax snapshots to fix the tests (UI has been slightly updated in the last API level)
> 
> What do I set `ICON_STAX` in the Makefile to? In the Boilerplate app it is a 32x32 image: https://github.com/LedgerHQ/app-boilerplate/blob/master/Makefile#L44. But the documentation says inside the app should be 64x64.
> 
> I also don't understand where I am supposed to set the dashboard icon because I can't find any reference to it in the boilerplate app: https://github.com/search?q=repo%3ALedgerHQ%2Fapp-boilerplate%20dashboard&type=code.

here you have the reference for the icon 32x32 for the app dashboard (device home screen):
https://github.com/LedgerHQ/app-boilerplate/blob/d7a48b22de3b16dc9ac87063a863e8c14925066d/Makefile#L44C1-L44C3

here you have the icon 64x64 for the app home screen:
https://github.com/LedgerHQ/app-boilerplate/blob/master/glyphs/app_boilerplate_64px.gif
which is used here for example:
https://github.com/LedgerHQ/app-boilerplate/blob/d7a48b22de3b16dc9ac87063a863e8c14925066d/src/ui/menu_nbgl.c#L85 and without forgetting this include:
https://github.com/LedgerHQ/app-boilerplate/blob/d7a48b22de3b16dc9ac87063a863e8c14925066d/src/ui/menu_nbgl.c#L22C1-L22C20

**Comment by chris124567** [comment]
Thank you for your help.  I created https://github.com/LedgerHQ/app-sia-x/pull/6 which updates ledger_app.toml and should fix all the icon issues and test issues.

**Comment by tdejoigny-ledger** [comment]
> Thank you for your help. I created #6 which updates ledger_app.toml and should fix all the icon issues and test issues.

ty  @chris124567 👍 
now all seem to be good. I close this PR (covered by your PR https://github.com/LedgerHQ/app-sia-x/pull/6) and I will merge your new PR.

**Comment by chris124567** [comment]
Great!  Let me know if there's anything else I need to do.

**Pull request closed without merging**
